/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Project;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.ImageIcon;
import java.io.FileWriter;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author Mosab M. Zaafan
 */
public class Data_Card extends javax.swing.JFrame {

    private void formWindowOpened(java.awt.event.WindowEvent evt) {
        for (double i = 0.0; i <= 1.0; i = i + 0.1) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(50);
            } catch (Exception e) {

            }
        }
    }

    /**
     * Creates new form Data_Card
     */
    public Data_Card() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Department = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        Job = new javax.swing.JTextField();
        Age = new javax.swing.JTextField();
        idText = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Salary1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(380, 100));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_card/Rectangle 3.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 80, 60));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Edit");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 40, 20));

        jLabel7.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Delete");
        jLabel7.setToolTipText("");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 60, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_Patients/icons8-person-100.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 110, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_card/Rectangle 30 (1) (1).png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 421, 102, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_card/Rectangle 28 (1) (1).png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 421, -1, -1));

        jLabel8.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Details");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 80, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_card/craiyon_152753_login_form_background.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 430, 33));

        jLabel9.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel9.setText("Name:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel10.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel10.setText("Job:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel11.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel11.setText("Departement:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

        id.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        id.setText("id:");
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jLabel13.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel13.setText("Age:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        Department.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Department.setBorder(null);
        Department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartmentActionPerformed(evt);
            }
        });
        jPanel1.add(Department, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 90, 30));

        Name.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Name.setToolTipText("");
        Name.setBorder(null);
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 110, 30));

        Job.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Job.setBorder(null);
        Job.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JobActionPerformed(evt);
            }
        });
        jPanel1.add(Job, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 110, 30));

        Age.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Age.setBorder(null);
        Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeActionPerformed(evt);
            }
        });
        jPanel1.add(Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 100, 30));

        idText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        idText.setBorder(null);
        idText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextActionPerformed(evt);
            }
        });
        jPanel1.add(idText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 110, 30));

        jLabel14.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel14.setText("Salary:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        Salary1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Salary1.setBorder(null);
        Salary1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salary1ActionPerformed(evt);
            }
        });
        jPanel1.add(Salary1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 110, 30));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("X");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 40, 29));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public Data_Card(int A, String D, String N, int i, String imger, double S) {
        initComponents();
        int age = A;
        if (imger.length() == 0) {
            imger = "src/icon_Patients/icons8-person-100.png";
        }
        ImageIcon icon = new ImageIcon(imger);
        String dep = D;
        String name = N;
        double sal = S;
        String job = "";
        int id = i;
        if (id / 10000 == 1) {
            job = "Doctor";
        } else if (id / 10000 == 2) {
            job = "Nurse";
        } else if (id / 10000 == 3) {
            job = "Staff Member";
        }

        this.Name.setText(name);
        this.Age.setText(age + "");
        this.Department.setText(dep);
        this.Job.setText(job);
        this.idText.setText(id + "");
        this.Salary1.setText(sal + "");
        this.jLabel3.setIcon(icon);
    }

    public Data_Card(int Age, String Department, String Name, int idText, String imger, String D) {
        initComponents();
        int age = Age;
        String dec = D;
        String dep = Department;
        if (imger.length() == 0) {
            imger = "src/icon_Patients/icons8-person-100.png";
        }
        ImageIcon icon = new ImageIcon(imger);
        String name = Name;
        int id = idText;
        String job = "Patient";
        this.Name.setText(name);
        this.Age.setText(age + "");
        this.Department.setText(dep);
        this.Job.setText(job);
        this.idText.setText(id + "");
        this.Salary1.setText(dec);
        this.jLabel14.setText("Dicease:");
        this.jLabel3.setIcon(icon);
    }


    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        Name.setEnabled(false);
    }//GEN-LAST:event_NameActionPerformed

    private void DepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepartmentActionPerformed

    private void AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeActionPerformed

    private void idTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void JobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JobActionPerformed

    private void Salary1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salary1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Salary1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        try {
            File musicPath = new File("converted_clicksound.wav");
            if (musicPath.exists()) {
                AudioInputStream audioInput = AudioSystem.getAudioInputStream(musicPath);
                Clip clip = AudioSystem.getClip();
                clip.open(audioInput);
                clip.start();
            } else {
                //System.out.println("Couldn't find Music file");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        int id_to_search = Integer.parseInt(this.idText.getText().trim());
        System.out.println(id_to_search);
        String pather = "";
        if (id_to_search / 10000 == 1) {
            pather = "src/JSON/doctor.json";
        } else if (id_to_search / 10000 == 2) {
            pather = "src/JSON/nurses.json";
        } else if (id_to_search / 10000 == 3) {
            pather = "src/JSON/staff.json";
        } else if (id_to_search / 10000 == 4) {
            pather = "src/JSON/patients.json";
        }

//*****************************files*******************************
        JSONParser jp = new JSONParser();
        JSONArray dataArray;

        try (FileReader read = new FileReader(pather)) {
            dataArray = (JSONArray) jp.parse(read);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
            return;
        } catch (IOException | ParseException e) {
            e.printStackTrace();
            return;
        }

        for (int i = 0; i < dataArray.size(); i++) {
            JSONObject ob = (JSONObject) dataArray.get(i);
            String idString = String.valueOf(ob.get("id"));

            if (Integer.parseInt(idString) == id_to_search && id_to_search / 10000 != 4) {
                ob.put("name", this.Name.getText());
                ob.put("id", this.idText.getText());
                ob.put("department", this.Department.getText());
                ob.put("salary", this.Salary1.getText());
                ob.put("age", this.Age.getText());
            } else if (Integer.parseInt(idString) == id_to_search && id_to_search / 10000 == 4) {
                ob.put("disease", this.Salary1.getText());
                ob.put("name", this.Name.getText());
                ob.put("id", this.idText.getText());
                ob.put("department", this.Department.getText());
                ob.put("age", this.Age.getText());
            }
        }

        try (FileWriter file = new FileWriter(pather)) {
            file.write(dataArray.toJSONString());
            file.flush();
        } catch (IOException e) {
            e.printStackTrace();
        }

        //*****************************files*******************************
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        try {
            File musicPath = new File("converted_clicksound.wav");
            if (musicPath.exists()) {
                AudioInputStream audioInput = AudioSystem.getAudioInputStream(musicPath);
                Clip clip = AudioSystem.getClip();
                clip.open(audioInput);
                clip.start();
            } else {
                //System.out.println("Couldn't find Music file");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        int id_to_search = Integer.parseInt(this.idText.getText().trim());
        System.out.println(id_to_search);
        String pather = "";
        if (id_to_search / 10000 == 1) {
            pather = "src/JSON/doctor.json";
        } else if (id_to_search / 10000 == 2) {
            pather = "src/JSON/nurses.json";
        } else if (id_to_search / 10000 == 3) {
            pather = "src/JSON/staff.json";
        } else if (id_to_search / 10000 == 4) {
            pather = "src/JSON/patients.json";
        }

//*****************************files*******************************
        JSONParser jp = new JSONParser();
        JSONArray dataArray;

        try (FileReader read = new FileReader(pather)) {
            dataArray = (JSONArray) jp.parse(read);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
            return;
        } catch (IOException | ParseException e) {
            e.printStackTrace();
            return;
        }

        for (int i = 0; i < dataArray.size(); i++) {
            JSONObject ob = (JSONObject) dataArray.get(i);
            String idString = String.valueOf(ob.get("id"));

            if (Integer.parseInt(idString) == id_to_search) {
                dataArray.remove(i);
            }
        }

        try (FileWriter file = new FileWriter(pather)) {
            file.write(dataArray.toJSONString());
            file.flush();
        } catch (IOException e) {
            e.printStackTrace();
        }

        //*****************************files*******************************
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        try {
            File musicPath = new File("converted_clicksound.wav");
            if (musicPath.exists()) {
                AudioInputStream audioInput = AudioSystem.getAudioInputStream(musicPath);
                Clip clip = AudioSystem.getClip();
                clip.open(audioInput);
                clip.start();
            } else {
                //System.out.println("Couldn't find Music file");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_Card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_Card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_Card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_Card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data_Card().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age;
    private javax.swing.JTextField Department;
    private javax.swing.JTextField Job;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Salary1;
    private javax.swing.JLabel id;
    private javax.swing.JTextField idText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
